substitutions:
  _PROJECT_ID: '$PROJECT_ID'
steps:
  #Build the container Image 
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$_PROJECT_ID/node-app:$SHORT_SHA", "."]
  # pusth the repo to container registry 
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$_PROJECT_ID/node-app:$SHORT_SHA" ]
   # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    secretEnv: ['DB_USER', 'DB_PASSWORD', 'DB_DATABASE', 'DB_HOST']
    args: 
     - run
     - deploy
     - node-api-service
     - --allow-unauthenticated
     - --set-env-vars=DB_USER=$$DB_USER
     - --set-env-vars=DB_PASS=$$DB_PASSWORD 
     - --set-env-vars=DB_DATABASE=$$DB_DATABASE 
     - --set-env-vars=DB_HOST=$$DB_HOST 
     - --image=gcr.io/$_PROJECT_ID/node-api:$SHORT_SHA
     - --region=us-central1
availableSecrets:
  secretManager:
  - versionName: projects/$_PROJECT_ID/secrets/DB_USER/versions/latest
    env: 'DB_USER'
  - versionName: projects/$_PROJECT_ID/secrets/DB_PASSWORD/versions/latest
    env: 'DB_PASSWORD'
  - versionName: projects/$_PROJECT_ID/secrets/DB_DATABASE/versions/latest
    env: 'DB_DATABASE'
  - versionName: projects/$_PROJECT_ID/secrets/DB_HOST/versions/latest
    env: 'DB_HOST'
