substitutions:
  _PROJECT_ID: '$PROJECT_ID'
steps:
  #Build the container Image 
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$_PROJECT_ID/node-api:$COMMIT_SHA", "."]
  # pusth the repo to container registry 
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$_PROJECT_ID/node-api:$COMMIT_SHA" ]
   # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
     - run
     - deploy
     - node-api-service
     - --allow-unauthenticated
     - --set-secrets=DB_USER=projects/$_PROJECT_ID/secrets/DB_USER:latest,DB_PASS=projects/$_PROJECT_ID/secrets/DB_PASSWORD:latest,DB_DATABASE=projects/$_PROJECT_ID/secrets/DB_DATABASE:latest,DB_HOST=projects/$_PROJECT_ID/secrets/DB_HOST/:latest,DB_PORT=projects/$_PROJECT_ID/secrets/DB_PORT:latest
     - --image=gcr.io/$_PROJECT_ID/node-api:$COMMIT_SHA
     - --vpc-connector=sqlconnect
     - --port=8080
     - --region=us-central1

